export const TENANT_CONTEXT_CRYPTO = Symbol('TENANT_CONTEXT_CRYPTO');
export const CENTER_APP_BASE_DOMAIN = Symbol('CENTER_APP_BASE_DOMAIN');
export const CENTER_APP_BASE_ORIGIN = Symbol('CENTER_APP_BASE_ORIGIN');
