-- Product migration 0000. Tables generated with Drizzle Kit from src/iam-schema.ts.
-- RLS, grants, and SECURITY DEFINER functions below the generated tables are reviewed SQL.
CREATE SCHEMA "iam_app";
--> statement-breakpoint
CREATE TABLE "iam_app"."audit_records" (
	"id" uuid NOT NULL,
	"tenant_id" uuid NOT NULL,
	"actor_identity_id" uuid NOT NULL,
	"action" text NOT NULL,
	"resource_type" text NOT NULL,
	"resource_id" uuid NOT NULL,
	"result" text NOT NULL,
	"reason" text,
	"correlation_id" uuid NOT NULL,
	"created_at" timestamp with time zone NOT NULL,
	CONSTRAINT "audit_records_tenant_id_id_pk" PRIMARY KEY("tenant_id","id")
);
--> statement-breakpoint
CREATE TABLE "iam_app"."centers" (
	"id" uuid NOT NULL,
	"tenant_id" uuid NOT NULL,
	"name" text NOT NULL,
	CONSTRAINT "centers_tenant_id_id_pk" PRIMARY KEY("tenant_id","id")
);
--> statement-breakpoint
CREATE TABLE "iam_app"."external_identities" (
	"identity_id" uuid NOT NULL,
	"issuer" text NOT NULL,
	"subject" text NOT NULL,
	CONSTRAINT "external_identities_issuer_subject_pk" PRIMARY KEY("issuer","subject"),
	CONSTRAINT "external_identities_identity_id_issuer_unique" UNIQUE("identity_id","issuer")
);
--> statement-breakpoint
CREATE TABLE "iam_app"."identities" (
	"id" uuid PRIMARY KEY NOT NULL
);
--> statement-breakpoint
CREATE TABLE "iam_app"."memberships" (
	"id" uuid NOT NULL,
	"tenant_id" uuid NOT NULL,
	"identity_id" uuid NOT NULL,
	"status" text NOT NULL,
	"roles" text[] NOT NULL,
	"center_ids" uuid[],
	CONSTRAINT "memberships_tenant_id_id_pk" PRIMARY KEY("tenant_id","id"),
	CONSTRAINT "memberships_tenant_id_identity_id_unique" UNIQUE("tenant_id","identity_id"),
	CONSTRAINT "memberships_status_known" CHECK (status IN ('pending', 'active', 'disabled')),
	CONSTRAINT "memberships_roles_known" CHECK (cardinality(roles) > 0 AND roles <@ ARRAY[
        'tenant_owner',
        'tenant_admin',
        'operations_lead',
        'auditor_compliance',
        'center_manager',
        'reception_booking_manager',
        'external_collaborator'
      ]::text[])
);
--> statement-breakpoint
CREATE TABLE "iam_app"."outbox_events" (
	"id" uuid NOT NULL,
	"tenant_id" uuid NOT NULL,
	"event_type" text NOT NULL,
	"payload" jsonb NOT NULL,
	"correlation_id" uuid NOT NULL,
	"idempotency_key" text NOT NULL,
	"created_at" timestamp with time zone NOT NULL,
	CONSTRAINT "outbox_events_tenant_id_id_pk" PRIMARY KEY("tenant_id","id"),
	CONSTRAINT "outbox_events_tenant_id_idempotency_key_unique" UNIQUE("tenant_id","idempotency_key")
);
--> statement-breakpoint
CREATE TABLE "iam_app"."tenants" (
	"id" uuid PRIMARY KEY NOT NULL,
	"name" text NOT NULL
);
--> statement-breakpoint
ALTER TABLE "iam_app"."audit_records" ADD CONSTRAINT "audit_records_tenant_id_tenants_id_fk" FOREIGN KEY ("tenant_id") REFERENCES "iam_app"."tenants"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "iam_app"."centers" ADD CONSTRAINT "centers_tenant_id_tenants_id_fk" FOREIGN KEY ("tenant_id") REFERENCES "iam_app"."tenants"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "iam_app"."external_identities" ADD CONSTRAINT "external_identities_identity_id_identities_id_fk" FOREIGN KEY ("identity_id") REFERENCES "iam_app"."identities"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "iam_app"."memberships" ADD CONSTRAINT "memberships_tenant_id_tenants_id_fk" FOREIGN KEY ("tenant_id") REFERENCES "iam_app"."tenants"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "iam_app"."memberships" ADD CONSTRAINT "memberships_identity_id_identities_id_fk" FOREIGN KEY ("identity_id") REFERENCES "iam_app"."identities"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "iam_app"."outbox_events" ADD CONSTRAINT "outbox_events_tenant_id_tenants_id_fk" FOREIGN KEY ("tenant_id") REFERENCES "iam_app"."tenants"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
-- Reviewed security SQL (not generated by Drizzle Kit): RLS, grants, resolver.
ALTER TABLE "iam_app"."tenants" ENABLE ROW LEVEL SECURITY;
--> statement-breakpoint
ALTER TABLE "iam_app"."tenants" FORCE ROW LEVEL SECURITY;
--> statement-breakpoint
ALTER TABLE "iam_app"."centers" ENABLE ROW LEVEL SECURITY;
--> statement-breakpoint
ALTER TABLE "iam_app"."centers" FORCE ROW LEVEL SECURITY;
--> statement-breakpoint
ALTER TABLE "iam_app"."memberships" ENABLE ROW LEVEL SECURITY;
--> statement-breakpoint
ALTER TABLE "iam_app"."memberships" FORCE ROW LEVEL SECURITY;
--> statement-breakpoint
ALTER TABLE "iam_app"."audit_records" ENABLE ROW LEVEL SECURITY;
--> statement-breakpoint
ALTER TABLE "iam_app"."audit_records" FORCE ROW LEVEL SECURITY;
--> statement-breakpoint
ALTER TABLE "iam_app"."outbox_events" ENABLE ROW LEVEL SECURITY;
--> statement-breakpoint
ALTER TABLE "iam_app"."outbox_events" FORCE ROW LEVEL SECURITY;
--> statement-breakpoint
CREATE POLICY tenants_isolation ON "iam_app"."tenants"
  USING (id = current_setting('app.tenant_id')::uuid)
  WITH CHECK (id = current_setting('app.tenant_id')::uuid);
--> statement-breakpoint
CREATE POLICY centers_isolation ON "iam_app"."centers"
  USING (tenant_id = current_setting('app.tenant_id')::uuid)
  WITH CHECK (tenant_id = current_setting('app.tenant_id')::uuid);
--> statement-breakpoint
CREATE POLICY memberships_isolation ON "iam_app"."memberships"
  USING (tenant_id = current_setting('app.tenant_id')::uuid)
  WITH CHECK (tenant_id = current_setting('app.tenant_id')::uuid);
--> statement-breakpoint
CREATE POLICY audit_isolation ON "iam_app"."audit_records"
  USING (tenant_id = current_setting('app.tenant_id')::uuid)
  WITH CHECK (tenant_id = current_setting('app.tenant_id')::uuid);
--> statement-breakpoint
CREATE POLICY outbox_isolation ON "iam_app"."outbox_events"
  USING (tenant_id = current_setting('app.tenant_id')::uuid)
  WITH CHECK (tenant_id = current_setting('app.tenant_id')::uuid);
--> statement-breakpoint
CREATE OR REPLACE FUNCTION iam_app.validate_membership_centers()
RETURNS trigger LANGUAGE plpgsql SET search_path = iam_app, pg_temp AS $$
BEGIN
  IF NEW.center_ids IS NOT NULL AND EXISTS (
    SELECT 1
    FROM unnest(NEW.center_ids) AS assigned(center_id)
    LEFT JOIN iam_app.centers AS center
      ON center.tenant_id = NEW.tenant_id AND center.id = assigned.center_id
    WHERE center.id IS NULL
  ) THEN
    RAISE EXCEPTION 'Invalid membership center scope' USING ERRCODE = '23503';
  END IF;
  RETURN NEW;
END $$;
--> statement-breakpoint
REVOKE ALL ON FUNCTION iam_app.validate_membership_centers() FROM PUBLIC;
--> statement-breakpoint
CREATE TRIGGER memberships_centers_same_tenant
BEFORE INSERT OR UPDATE OF tenant_id, center_ids ON iam_app.memberships
FOR EACH ROW EXECUTE FUNCTION iam_app.validate_membership_centers();
--> statement-breakpoint
CREATE OR REPLACE FUNCTION iam_app.resolve_access(p_issuer text, p_subject text, p_tenant uuid)
RETURNS jsonb LANGUAGE plpgsql STABLE SECURITY DEFINER SET search_path = iam_app, pg_temp AS $$
DECLARE result jsonb;
BEGIN
  PERFORM set_config('app.tenant_id', p_tenant::text, true);
  SELECT jsonb_build_object(
    'identityId', i.id,
    'membershipId', m.id,
    'tenantId', m.tenant_id,
    'roles', m.roles,
    'centerIds', m.center_ids
  ) INTO result
  FROM iam_app.external_identities e
  JOIN iam_app.identities i ON i.id = e.identity_id
  JOIN iam_app.memberships m ON m.identity_id = i.id AND m.tenant_id = p_tenant
  WHERE e.issuer = p_issuer AND e.subject = p_subject AND m.status = 'active';
  RETURN result;
END $$;
--> statement-breakpoint
REVOKE ALL ON FUNCTION iam_app.resolve_access(text, text, uuid) FROM PUBLIC;
--> statement-breakpoint
GRANT EXECUTE ON FUNCTION iam_app.resolve_access(text, text, uuid) TO dive_app;
--> statement-breakpoint
GRANT USAGE ON SCHEMA iam_app TO dive_app;
--> statement-breakpoint
REVOKE ALL ON iam_app.tenants, iam_app.centers, iam_app.memberships, iam_app.audit_records, iam_app.outbox_events FROM dive_app;
--> statement-breakpoint
GRANT SELECT ON iam_app.tenants, iam_app.centers, iam_app.memberships TO dive_app;
--> statement-breakpoint
GRANT UPDATE (status) ON iam_app.memberships TO dive_app;
--> statement-breakpoint
GRANT INSERT ON iam_app.audit_records, iam_app.outbox_events TO dive_app;
--> statement-breakpoint
REVOKE ALL ON iam_app.identities, iam_app.external_identities FROM dive_app;
